### ISSUE TITLE
No están los datos para correr el código de R de "ejemploGDP"

### ISSUE THREAD

**Issue by jmariasm1** [sbohorquez/SeriesdeTiempo#3]
En el siguiente link les comparto el archivo que pueden usar para poder hacer el ejemplo. 
https://eafit-my.sharepoint.com/:x:/g/personal/jmariasm1_eafit_edu_co/EZoEfrTAPSRPpqtkF0fTn3MBlUHy7jBSByYe28IL1FMGyA

**Comment by sbohorquez** [comment]
Gracias por la corrección, ya subi los datos correctos.
