### ISSUE TITLE
Errores diapositivas

### ISSUE THREAD

**Issue by iarangor1** [sbohorquez/SeriesdeTiempo#4]
Hola profe, revisando las diapositivas encontré diferentes errores que me parece importante corregir. Te los listo a continuación:

1. **Diapositivas Modelos ARIMA:** En la sección 35 se realiza la estimación de auto-covarianzas para el modelo AR(p) y para eso se comienza definiendo \gamma_0, pero está escrito como  \gamma_j
![image](https://user-images.githubusercontent.com/41337664/159543750-e3241e6f-8d13-47c5-9270-3ccf2e0f97b5.png)

2. **Diapositivas Características:** En la sección 27, cuando se define la condición que debe satisfacer cualquier combinación, la sumatoria está en términos de j, pero los sumandos en términos de i
![image](https://user-images.githubusercontent.com/41337664/159545805-7e69bd1a-0b6d-4cee-8646-18f7236cbbb2.png)

3. **Diapositivas Validación:** En la sección 3, cuando se define \varepsilon_t estimado se escribe nuevamente \varepsilon_t original
![image](https://user-images.githubusercontent.com/41337664/159547315-97cd55e7-300d-49f8-8fec-b52fa37a2ef0.png)

**Comment by sbohorquez** [comment]
Se hicieron las correcciones, gracias.
