### ISSUE TITLE
Errores en las diapositivas

### ISSUE THREAD

**Issue by vmendozai** [sbohorquez/SeriesdeTiempo#5]
1) En la diapositiva 'Características', en la página 'ergodicidad'. Error de digitación
![error1](https://user-images.githubusercontent.com/41337759/159548974-054606c0-4714-42d0-a905-7212c0df57d1.jpg)

2) En la diapositiva 'Características', en la página 'procesos-estacionarios-en-tendencia'. Error de digitación
![image](https://user-images.githubusercontent.com/41337759/159549648-0bbbd15e-4451-4345-92f2-b7a871718ab6.png)

3) En la diapositiva 'Modelos ARIMA', en la página 'section-21'. Error: falta corchete en la quinta igualdad de la varianza 
![image](https://user-images.githubusercontent.com/41337759/159551015-897eff7d-0491-4d3e-b301-890ff58d7234.png)

**Comment by sbohorquez** [comment]
Se hicieron las correcciones, gracias.
