### ISSUE TITLE
Correcciones para hacer en las diapositivas

### ISSUE THREAD

**Issue by marianagomez** [sbohorquez/SeriesdeTiempo#6]
1. Diapositivas de identificación, el error está en la página 7 y es que hay un (++) que no hace referencia a nada, entonces debe ser (+)
2. En las diapositivas de estimación en la sección 44 hay un error en la digitación de látex en el último ítem
3. En las diapositivas de validación en la sección 13 hay un error de digitación de látex

**Comment by sbohorquez** [comment]
Se hicieron las correcciones, gracias.
