### ISSUE TITLE
Corrección en Diapositivas

### ISSUE THREAD

**Issue by hamiltonSgomezO** [sbohorquez/SeriesdeTiempo#7]
Buenos días, profe

Te quería dejar por aquí algunas correcciones oportunas en las diapositivas que identifiqué hace algún tiempo:

- Diapositivas validación - sección 7: sobra un paréntesis
- Diapositivas estimación - sección 50, 51 y 52: falta un corchete

Adicionalmente, en la última clase dijiste que en las diapositivas de Modelos Estacionales que las sumatorias empezaban desde cero pero que debían estar desde uno, por lo que te dejo la acotación por si deseas revisarlo y ver si ese es el caso.

**Comment by sbohorquez** [comment]
Hola,

Sehicieron las correcciones. Gracais
